Variadic sourcegen
genaray/Arch pull request #166
Opened 2023-10-28 06:14 UTC by LilithSilver

Currently, the Arch source-generation is pretty clunky. There's no compilation validation at all, making edits on the codebase hell.

This PR introduces a "variadic source generator", similar to variadic templates in C++. It makes variadic generics.. well, generic!

For example, you can specify a variadic like so...

```
public static partial class EntityExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    [Pure]
    [Variadic(nameof(T1), 2, 25)]
    public static bool Has<T0, T1>(this Entity entity)
    {
        var world = World.Worlds[entity.WorldId];
        return world.Has<T0, T1>(entity);
    }
```

This signature will be the very first variadic generated, so it'll generate `<T0, T1, T3>` onwards up to `<T0 ... T24>` (total count 25).

It additionally puts each variadic in separate files like this:
![image](https://github.com/genaray/Arch/assets/84940819/4422e531-6cb6-4343-81c0-2d226985567b)
This enables easier debugging instead of one monolithic file.

2023-10-30 15:40 UTC, genaray commented
Sounds great! One question tho. Is the same output produced? E.g. many source generated overloads make use of the batched operations e.g. : `Index<T0,,,T25>(out indexOne, indextwo, ..).` ^^

2023-10-30 17:11 UTC, LilithSilver commented
> Sounds great! One question tho. Is the same output produced? E.g. many source generated overloads make use of the batched operations e.g. : `Index<T0,,,T25>(out indexOne, indextwo, ..).` ^^

Yep, I'm using the original sourcegen as a guide! Variable names might be different but the code should semantically be the same.

Cool, I'll convert everything over then.

2023-11-01 18:36 UTC, lewis-savage commented
Is there a reason for the change of variable names from t0, t1 etc to Component__T0, Component__T1?
This will require all users to update the usages, unless I'm missing something

2023-11-01 20:50 UTC, LilithSilver commented
> Is there a reason for the change of variable names from t0, t1 etc to Component__T0, Component__T1?

This is because it's much easier to have a common variable/parameter format for the variadic source generator to hook into. We could switch back to t0Component etc but it would more effort and be more finicky, since it doesn't map directly to the type. 

> This will require all users to update the usages, unless I'm missing something

There are only two situations which require user intervention here:
* The user was specifying parameters by name instead of by order. I don't think this is very common for the generic overloads, but it will cause them to change the specified parameter names on upgrade. 
* The user was using Component<...> or EntityComponent<...> directly and setting t0, t1, etc. In the case, those old fields were breaking standard of upper case field names for public fields.

2023-11-06 16:21 UTC, genaray requested changes
Finally had some time to look at the pr ^^ 
Looks good so far, kinda confusing since its source-gen. So i requested a few changes for clarity. Also... do we really require those doubled .Has e.g. methods? We could make it so that we just mark the single generics with variadic?

2023-11-06 16:21 UTC, genaray commented on src/Arch.Benchmarks/QueryBenchmark.cs
> +            refs.Component__T0.X += refs.Component__T1.X;
I also think that the old syntax should be adapted here. Or that there is at least one less underscore there: `Component_T0`.

2023-11-06 16:21 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +        StringBuilder transformed = new();
var ... = new StringBuilder(); instead? 
And for all following samples to match the code-style? ^^

2023-11-06 16:21 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Is there any way to make this more readable? ^^ (For the marked lines and all following source-gen stuff). 

In the past i used those nice string templates: 
```csharp
var template = $"""
   {MethodName}<{Generics}>({Params});
"""
```

Just as example. MethodName, Generics and Params would be StringBuilders which then get inserted there.
I personally prefer this since its more readable in my opinion ^^

2023-11-06 16:21 UTC, genaray commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                    if (attr.AttributeClass?.Name == "VariadicAttribute")
Splitting this up into multiple methods for readability? 
Also the new lines under this, couldn't mark them unfortunately.

2023-11-06 16:21 UTC, genaray commented on src/Arch.SourceGen/VariadicGenerator.cs
> +    private string MakeVariadic(VariadicInfo info)
Docs for the other methods and structs? ^^

2023-11-06 16:21 UTC, genaray commented on src/Arch/Core/Variadics/Archetype.Variadics.cs
> +    public bool Has<T0, T1>()
Why are those required? We already have them as single generics (or?)? ^^ 
Couldnt we just mark those existing methods to generate variadics?

2023-11-06 17:34 UTC, LilithSilver commented on src/Arch.Benchmarks/QueryBenchmark.cs
> +            refs.Component__T0.X += refs.Component__T1.X;
I'll use a single underscore! It'll be much simpler to implement.

2023-11-06 17:37 UTC, LilithSilver commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Hmm, I'm not sure. The problem is, this method can be used to copy args into anything. For example, `MyMethod1(arg, MyMethod2(typedArgs))` would break...

Any thoughts on this case?

2023-11-06 17:59 UTC, LilithSilver commented on src/Arch/Core/Variadics/Archetype.Variadics.cs
> +    public bool Has<T0, T1>()
I agree!

But my goal with this PR was to exactly mirror the current generated code, line by line. And they're currently split up like this.

So maybe we could combine methods like this in a future PR? What do you think?

2023-11-07 01:16 UTC, distantcam commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                    var reference = ctx.TargetSymbol.ContainingType.IsReferenceType ? "class" : "struct";
Records are also reference types. This works for now but I believe a future version of C# will introduce record structs.

```suggestion
                    var reference = ctx.TargetSymbol.ContainingType.IsRecord ? "record" :  ctx.TargetSymbol.ContainingType.IsValueType ? "struct" : "class";
```

2023-11-07 01:25 UTC, distantcam commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                    info.EnclosingType = $"{accessibility} partial {reference} {ctx.TargetSymbol.ContainingType.Name}";
Will change generic types from Name`1 to Name<T> for example.
```suggestion
                   var typeName = ctx.TargetSymbol.ContainingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                    info.EnclosingType = $"{accessibility} partial {reference} {typeName}";
```

2023-11-07 01:25 UTC, distantcam commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                info.Name = ctx.TargetSymbol.Name;
```suggestion
                info.Name = typeName;
```

2023-11-07 03:04 UTC, LilithSilver commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                    var reference = ctx.TargetSymbol.ContainingType.IsReferenceType ? "class" : "struct";
Record structs actually exist in C#10 already. I'll make sure those are supported.

2023-11-07 03:34 UTC, distantcam commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                    var reference = ctx.TargetSymbol.ContainingType.IsReferenceType ? "class" : "struct";
You're right! I am behind.

2023-11-07 10:42 UTC, LilithSilver commented on src/Arch.SourceGen/VariadicGenerator.cs
> +                info.Name = ctx.TargetSymbol.Name;
This one won't work because info.Name is for naming the files, and `<` and `>` can't be in filenames. Got the other one though!

2023-11-07 10:43 UTC, LilithSilver commented
OK, fixed what I could til I get more info from genaray, and did another documentation pass. Thanks for the feedback, both of you!

2023-11-09 01:08 UTC, genaray commented on src/Arch/Core/Variadics/Archetype.Variadics.cs
> +    public bool Has<T0, T1>()
Ah, I see... mhmm... I think they should definitely still be "memorized". I think it would make more sense and the code would be easier to understand ^^ But I don't really care if it happens now or later.

2023-11-09 01:09 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Hmm okay I see. Well then, such templates would probably be a bit out of place. Do you have any other ideas to make the code more readable? The problem is that the task of the methods is sometimes so complex and full of string builders that you can hardly see through them. Especially if you're just learning the ropes ^^

2023-11-09 01:10 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Maybe some other kind of abstraction so that the understanding arises? Maybe use such templates in a smaller style? Or recursively?

2023-11-09 08:41 UTC, LilithSilver commented on src/Arch/Core/Variadics/Archetype.Variadics.cs
> +    public bool Has<T0, T1>()
OK, I'll make an issue to track it once this PR is merged :+1:

2023-11-09 08:52 UTC, LilithSilver commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Yeah I agree. It's not easy to read, especially with the regex.

The ""correct"" solution is to use a CSharpSyntaxRewriter, but that introduces a whole host of new problems that we'd have to make custom algorithms to solve, and I find it actually much harder to read. So not that.

One idea is to make a static Utils class that contains methods with individual options, like one that expands `T0>` to `T0...>`, etc. And then each algorithm can just apply those to a string over and over. That way, it can be thought of as individual steps of string transformation, which is really what's happening here, and the gross regex can be kept to Utils and well documented.

I'll play around with that and see if I can make it more readable.

2023-11-09 12:55 UTC, LilithSilver commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
OK, I pushed a hopefully more clear implementation... it's definitely simpler and has more code-reuse, at least. Let me know when you think!

2023-11-10 18:14 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
> OK, I pushed a hopefully more clear implementation... it's definitely simpler and has more code-reuse, at least. Let me know when you think!

Im gonna look at it ^^ i guess it looks way more readable now, at least from the first look. Still inspecting

2023-11-14 00:13 UTC, genaray commented on src/Arch.SourceGen/CopyArgsAlgorithm.cs
> +    }
Took a while, life is busy rn. But that looks like its resolved, much more understandable :) Good job

2023-11-14 00:14 UTC, genaray commented
Alright the previous concerns were fixed ^^ 
I still need to take another look at one or two other parts, that should be done in the following days.

2024-04-10 11:19 UTC, closed without merging

2024-04-10 11:19 UTC, LilithSilver commented
Closing this for now since it's gone stale, and I don't have time to keep an eye on it -- if at some point you want to integrate this, feel free to re-open!